# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

name: got-scotch-api
channels:
- conda-forge
- defaults
dependencies:
- notebook=5.0
- pandas=0.17.1
- jupyter_kernel_gateway=2.0
